version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Produção também na porta 3001 externa
    environment:
      - NODE_ENV=production